package entities;
// Generated 18-may-2016 15:38:58 by Hibernate Tools 4.3.1.Final

/**
 * Alumno generated by hbm2java
 */
public class Alumno implements java.io.Serializable {

	private int idUsuario;
	private Centro centro;
	private Especializacion especializacion;
	private FamiliaProfesional familiaProfesional;
	private Grado grado;
	private Tutor tutor;
	private Usuario usuario;
	private Integer expediente;

	public Alumno() {
	}

	public Alumno(Centro centro, Especializacion especializacion, FamiliaProfesional familiaProfesional, Grado grado,
			Tutor tutor, Usuario usuario) {
		this.centro = centro;
		this.especializacion = especializacion;
		this.familiaProfesional = familiaProfesional;
		this.grado = grado;
		this.tutor = tutor;
		this.usuario = usuario;
	}

	public Alumno(Centro centro, Especializacion especializacion, FamiliaProfesional familiaProfesional, Grado grado,
			Tutor tutor, Usuario usuario, Integer expediente) {
		this.centro = centro;
		this.especializacion = especializacion;
		this.familiaProfesional = familiaProfesional;
		this.grado = grado;
		this.tutor = tutor;
		this.usuario = usuario;
		this.expediente = expediente;
	}

	public int getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(int idUsuario) {
		this.idUsuario = idUsuario;
	}

	public Centro getCentro() {
		return this.centro;
	}

	public void setCentro(Centro centro) {
		this.centro = centro;
	}

	public Especializacion getEspecializacion() {
		return this.especializacion;
	}

	public void setEspecializacion(Especializacion especializacion) {
		this.especializacion = especializacion;
	}

	public FamiliaProfesional getFamiliaProfesional() {
		return this.familiaProfesional;
	}

	public void setFamiliaProfesional(FamiliaProfesional familiaProfesional) {
		this.familiaProfesional = familiaProfesional;
	}

	public Grado getGrado() {
		return this.grado;
	}

	public void setGrado(Grado grado) {
		this.grado = grado;
	}

	public Tutor getTutor() {
		return this.tutor;
	}

	public void setTutor(Tutor tutor) {
		this.tutor = tutor;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public Integer getExpediente() {
		return this.expediente;
	}

	public void setExpediente(Integer expediente) {
		this.expediente = expediente;
	}

}
