package entities;
// Generated 18-may-2016 15:38:58 by Hibernate Tools 4.3.1.Final


import java.util.ArrayList;
import entities.Alumno.*;

import entities.FamiliaProfesional.*;

/**
 * Centro generated by hbm2java
 */
public class Centro implements java.io.Serializable {

	private Integer idCentro;
	private String nombreCentro;
	private ArrayList<Alumno> alumno = new ArrayList<Alumno>();
	private ArrayList<FamiliaProfesional> familiaProfesional = new ArrayList<FamiliaProfesional>();

	public Centro() {
	}

	public Centro(String nombreCentro) {
		this.nombreCentro = nombreCentro;
	}

	public Centro(String nombreCentro, ArrayList<Alumno> alumno, ArrayList<FamiliaProfesional> familiaProfesional) {
		this.nombreCentro = nombreCentro;
		this.alumno = alumno;
		this.familiaProfesional = familiaProfesional;
	}

	public Integer getIdCentro() {
		return this.idCentro;
	}

	public void setIdCentro(Integer idCentro) {
		this.idCentro = idCentro;
	}

	public String getNombreCentro() {
		return this.nombreCentro;
	}

	public void setNombreCentro(String nombreCentro) {
		this.nombreCentro = nombreCentro;
	}

	public ArrayList<Alumno> getAlumno() {
		return this.alumno;
	}

	public void setAlumno(ArrayList<Alumno> alumno) {
		this.alumno = alumno;
	}

	
	public ArrayList<FamiliaProfesional> getFamiliaProfesional() {
		return this.familiaProfesional;
	}

	public void setFamiliaProfesional(ArrayList<FamiliaProfesional> familiaProfesional) {
		this.familiaProfesional = familiaProfesional;
	}

}
