package entities;
// Generated 18-may-2016 15:38:58 by Hibernate Tools 4.3.1.Final

/**
 * DatosContacto generated by hbm2java
 */
public class DatosContacto implements java.io.Serializable {

	private int idUsuario;
	private Usuario usuario;
	private int telefono;
	private String email;

	public DatosContacto() {
	}

	public DatosContacto(Usuario usuario, int telefono, String email) {
		this.usuario = usuario;
		this.telefono = telefono;
		this.email = email;
	}

	public int getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(int idUsuario) {
		this.idUsuario = idUsuario;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public int getTelefono() {
		return this.telefono;
	}

	public void setTelefono(int telefono) {
		this.telefono = telefono;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

}
