package entities;
// Generated 18-may-2016 15:38:58 by Hibernate Tools 4.3.1.Final

import java.util.ArrayList;
import java.util.HashSet;
import java.util.Set;
import entities.Alumno.*;
import entities.Grado.*;

/**
 * Especializacion generated by hbm2java
 */
public class Especializacion implements java.io.Serializable {

	private Integer idEspecializacion;
	private String nombre;
	private ArrayList<Alumno> alumno = new ArrayList<Alumno>();
	private ArrayList<Grado> grado = new ArrayList<Grado>();

	public Especializacion() {
	}

	public Especializacion(String nombre) {
		this.nombre = nombre;
	}

	public Especializacion(String nombre, ArrayList<Alumno> alumno, ArrayList<Grado> grado) {
		this.nombre = nombre;
		this.alumno = alumno;
		this.grado = grado;
	}

	public Integer getIdEspecializacion() {
		return this.idEspecializacion;
	}

	public void setIdEspecializacion(Integer idEspecializacion) {
		this.idEspecializacion = idEspecializacion;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public ArrayList<Alumno> getAlumnos() {
		return this.alumno;
	}

	public void setAlumno(ArrayList<Alumno> alumno) {
		this.alumno = alumno;
	}

	public ArrayList<Grado> getGrado() {
		return this.grado;
	}

	public void setGrados(ArrayList<Grado> grado) {
		this.grado = grado;
	}

}
