package entities;
// Generated 18-may-2016 15:38:58 by Hibernate Tools 4.3.1.Final

import java.util.ArrayList;
import entities.Centro;
import entities.Usuario;
import entities.Alumno;
import entities.Centro;



/**
 * FamiliaProfesional generated by hbm2java
 */
public class FamiliaProfesional implements java.io.Serializable {

	private Integer idFamiliaProfesional;
	private String nombre;
	private ArrayList<Centro> centro = new ArrayList<Centro>(0);
	private ArrayList<Usuario> usuario = new ArrayList<Usuario>(0);
	private ArrayList<Alumno> alumno = new ArrayList<Alumno>(0);
	private ArrayList<Grado> grado = new ArrayList<Grado>(0);

	public FamiliaProfesional() {
	}

	public FamiliaProfesional(String nombre) {
		this.nombre = nombre;
	}

	public FamiliaProfesional(String nombre, ArrayList<Centro> centro, ArrayList<Usuario> usuario, ArrayList<Alumno> alumno,
			ArrayList<Grado> grado) {
		this.nombre = nombre;
		this.centro = centro;
		this.usuario = usuario;
		this.alumno = alumno;
		this.grado = grado;
	}

	public Integer getIdFamiliaProfesional() {
		return this.idFamiliaProfesional;
	}

	public void setIdFamiliaProfesional(Integer idFamiliaProfesional) {
		this.idFamiliaProfesional = idFamiliaProfesional;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public ArrayList<Centro> getCentro() {
		return this.centro;
	}

	public void setCentro(ArrayList<Centro> centro) {
		this.centro = centro;
	}

	public ArrayList<Usuario> getUsuario() {
		return this.usuario;
	}

	public void setUsuario(ArrayList<Usuario> usuario) {
		this.usuario = usuario;
	}

	public ArrayList<Alumno> getAlumno() {
		return this.alumno;
	}

	public void setAlumno(ArrayList<Alumno> alumno) {
		this.alumno = alumno;
	}

	public ArrayList<Grado> getGrado() {
		return this.grado;
	}

	public void setGrado(ArrayList<Grado> grado) {
		this.grado = grado;
	}

}
