package entities;
// Generated 18-may-2016 15:38:58 by Hibernate Tools 4.3.1.Final

import java.util.ArrayList;
import entities.Tutor.*;

/**
 * Profesor generated by hbm2java
 */
public class Profesor implements java.io.Serializable {

	private int idUsuario;
	private Usuario usuario;
	private String materias;
	private int idCentro;
	private ArrayList<Tutor> tutor = new ArrayList<Tutor>();
	private ArrayList<FamiliaProfesional> familiaProfesional = new ArrayList<FamiliaProfesional>();
	private ArrayList<Especializacion> especializacion = new ArrayList<Especializacion>();
	private ArrayList<Grado> grado = new ArrayList<Grado>();

	public Profesor() {
	}

	public Profesor(Usuario usuario, String materias, int idCentro) {
		this.usuario = usuario;
		this.materias = materias;
		this.idCentro = idCentro;
	}

	public Profesor(Usuario usuario, String materias, int idCentro, ArrayList<Tutor> tutor, ArrayList<FamiliaProfesional> familiaProfesional,
		ArrayList<Especializacion> especializacion, ArrayList<Grado> grado) {
		this.usuario = usuario;
		this.materias = materias;
		this.idCentro = idCentro;
		this.tutor = tutor;
		this.especializacion = especializacion;
		this.familiaProfesional = familiaProfesional;
		this.grado = grado;
	}

	public int getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(int idUsuario) {
		this.idUsuario = idUsuario;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public String getMaterias() {
		return this.materias;
	}

	public void setMaterias(String materias) {
		this.materias = materias;
	}

	public int getIdCentro() {
		return this.idCentro;
	}

	public void setIdCentro(int idCentro) {
		this.idCentro = idCentro;
	}

	public ArrayList<FamiliaProfesional> getFamiliaProfesional() {
		return this.familiaProfesional;
	}

	public void setFamiliaProfesional(ArrayList<FamiliaProfesional> familiaProfesional) {
		this.familiaProfesional = familiaProfesional;
	}
	
	public ArrayList<Grado> getGrado() {
		return this.grado;
	}

	public void setGrado(ArrayList<Grado> grado) {
		this.grado = grado;
	}
	
	public ArrayList<Especializacion> getEspecializacion() {
		return this.especializacion;
	}

	public void setEspecializacion(ArrayList<Especializacion> especializacion) {
		this.especializacion = especializacion;
	}

}
