package entities;
// Generated 18-may-2016 15:38:58 by Hibernate Tools 4.3.1.Final


import java.util.ArrayList;
import entities.Usuario.*;

/**
 * TipoUsuario generated by hbm2java
 */
public class TipoUsuario implements java.io.Serializable {

	private Integer idTipoUsuario;
	private String nombre;
	private ArrayList<Usuario> usuario = new ArrayList<Usuario>();

	public TipoUsuario() {
	}

	public TipoUsuario(String nombre) {
		this.nombre = nombre;
	}

	public TipoUsuario(String nombre, ArrayList<Usuario> usuario) {
		this.nombre = nombre;
		this.usuario = usuario;
	}

	public Integer getIdTipoUsuario() {
		return this.idTipoUsuario;
	}

	public void setIdTipoUsuario(Integer idTipoUsuario) {
		this.idTipoUsuario = idTipoUsuario;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public ArrayList<Usuario> getUsuario() {
		return this.usuario;
	}

	public void setUsuario(ArrayList<Usuario> usuario) {
		this.usuario = usuario;
	}

}
