package entities;
// Generated 18-may-2016 15:38:58 by Hibernate Tools 4.3.1.Final

import java.util.ArrayList;
import entities.Alumno.*;
import entities.Profesor.*;

/**
 * Tutor generated by hbm2java
 */
public class Tutor implements java.io.Serializable {

	private int idUsuario;
	private Empresa empresa;
	private ResponsableEmpresa responsableEmpresa;
	private Usuario usuario;
	private String nombre;
	private ArrayList<Profesor> profesor = new ArrayList<Profesor>();
	private ArrayList<Alumno> alumno = new ArrayList<Alumno>();

	public Tutor() {
	}
	
	public Tutor(String nombre) {
		this.nombre = nombre;
	}

	public Tutor(Empresa empresa, ResponsableEmpresa responsableEmpresa, Usuario usuario, String nombre) {
		this.empresa = empresa;
		this.responsableEmpresa = responsableEmpresa;
		this.usuario = usuario;
		this.nombre = nombre;
	}

	public Tutor(Empresa empresa, ResponsableEmpresa responsableEmpresa, Usuario usuario, ArrayList<Profesor> profesor,
			ArrayList<Alumno> alumno, String nombre) {
		this.empresa = empresa;
		this.responsableEmpresa = responsableEmpresa;
		this.usuario = usuario;
		this.profesor = profesor;
		this.alumno = alumno;
		this.nombre = nombre;
	}

	public int getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(int idUsuario) {
		this.idUsuario = idUsuario;
	}

	public Empresa getEmpresa() {
		return this.empresa;
	}

	public void setEmpresa(Empresa empresa) {
		this.empresa = empresa;
	}

	public ResponsableEmpresa getResponsableEmpresa() {
		return this.responsableEmpresa;
	}

	public void setResponsableEmpresa(ResponsableEmpresa responsableEmpresa) {
		this.responsableEmpresa = responsableEmpresa;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public ArrayList<Profesor> getProfesor() {
		return this.profesor;
	}

	public void setProfesor(ArrayList<Profesor> profesor) {
		this.profesor = profesor;
	}

	public ArrayList<Alumno> getAlumno() {
		return this.alumno;
	}

	public void setAlumno(ArrayList<Alumno> alumno) {
		this.alumno = alumno;
	}
	
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

}
