package entities;
// Generated 18-may-2016 15:38:58 by Hibernate Tools 4.3.1.Final

/**
 * Login generated by hbm2java
 */
public class Login implements java.io.Serializable {

	private Integer idLogin;
	private String username;
	private String password;
	private Usuario usuario;

	public Login() {
	}

	public Login(String username, String password) {
		this.username = username;
		this.password = password;
	}

	public Login(String username, String password, Usuario usuario) {
		this.username = username;
		this.password = password;
		this.usuario = usuario;
	}

	public Integer getIdLogin() {
		return this.idLogin;
	}

	public void setIdLogin(Integer idLogin) {
		this.idLogin = idLogin;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

}
