package entities;
// Generated 18-may-2016 15:38:58 by Hibernate Tools 4.3.1.Final

import java.util.ArrayList;
import entities.Tutor.*;

/**
 * ResponsableEmpresa generated by hbm2java
 */
public class ResponsableEmpresa implements java.io.Serializable {

	private int idUsuario;
	private Empresa empresa;
	private Usuario usuario;
	private ArrayList<Tutor> tutor = new ArrayList<Tutor>();

	public ResponsableEmpresa() {
	}

	public ResponsableEmpresa(Empresa empresa, ArrayList<Tutor> tutor) {
		this.empresa = empresa;
		this.tutor = tutor;
	}

	public ResponsableEmpresa(Empresa empresa, Usuario usuario, ArrayList<Tutor> tutor) {
		this.empresa = empresa;
		this.usuario = usuario;
		this.tutor = tutor;
	}

	public int getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(int idUsuario) {
		this.idUsuario = idUsuario;
	}

	public Empresa getEmpresa() {
		return this.empresa;
	}

	public void setEmpresa(Empresa empresa) {
		this.empresa = empresa;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public ArrayList<Tutor> getTutor() {
		return this.tutor;
	}

	public void setTutor(ArrayList<Tutor> tutor) {
		this.tutor = tutor;
	}

}
